#!/usr/bin/python3
def raise_exception():
    def raise_exception():
        raise ValueError('A very specific bad thing happened.')
